### PR TITLE
Localized

### PR DESCRIPTION
**Pull request by Fice**
Allow the usage of ugettext_lazy to localize the breadcrumbs

### CODE REVIEW

**Comment by kirelagin** [comment]
Is it really important to use lazy translations with crumbs? I haven’t tested that but I feel that their text is only ever accessed when rendering the template and it should be totally fine to use ordinary (non-lazy) strings. Am I wrong?

I’ll merge the PR anyway, but that’s an important question because if only lazy translations can be used for some reason, I’ll have to mention this in the README.

**Comment by Fice** [comment]
It didn't work for me, I always got the english label, even when I was viewing the german version. I think that makes sense, the decorator isn't instantiated everytime you call the view but only once. But if you use ugettext() it will immediately return the translated string, so the decorator only gets the already translated string and there is no actual translation happening when the view is called.
Just checked, force_text() is not needed, so I removed that.

BTW: my 2nd commit changes the readme and mentions that you have to use lazy translation.

**Comment by kirelagin** [comment]
Yes, of course, you are right, this totally makes sense.

**Comment by Fice** [comment]
yes, works fine without six.text_types. I have force pushed the removal

**Comment by kirelagin** [comment]
I’ve completely reworked the logic of detecting `callable`s in 5abc9a952c56eda448b331d17c7824c587059267 and I think this should work better, but, honestly, I haven’t tested it much. Please let me know if something is still not working.

Thanks!

**Pull request closed without merging**
